/* eslint-disable */
/* oxlint-disable */
// Auto-generated by @contentrain/query — do not edit manually
// Re-generate with: npx contentrain-query generate

export type ContentStatus = 'draft' | 'published' | 'in_review' | 'rejected' | 'archived'

export interface ChangelogEntry {
  slug: string
  content: string
  release_date: string
  slug: string
  summary?: string
  title: string
}

export interface DashboardOverview {
  environment_badge?: string
  eyebrow?: string
  primary_cta_href?: string
  primary_cta_label?: string
  status_note?: string
  summary: string
  title: string
}

export interface DashboardStat {
  id: string
  delta?: string
  label: string
  note?: string
  trend?: 'up' | 'down' | 'steady'
  value: string
}

export interface DocsPage {
  slug: string
  content: string
  description?: string
  layout?: 'doc'
  order?: number
  sidebar_label?: string
  slug: string
  title: string
}

export interface Feature {
  id: string
  emphasis?: boolean
  icon?: string
  summary: string
  title: string
}

export interface Footer {
  blurb?: string
  columns?: { links?: { href: string; label: string }[]; title: string }[]
  legal_notice?: string
}

export interface GuidePage {
  slug: string
  content: string
  description?: string
  order?: number
  sidebar_label?: string
  slug: string
  title: string
}

export interface Hero {
  eyebrow?: string
  hero_media?: string
  primary_cta_href?: string
  primary_cta_label?: string
  secondary_cta_href?: string
  secondary_cta_label?: string
  subtitle?: string
  title: string
}

export interface Integration {
  id: string
  category?: string
  icon?: string
  name: string
  slug: string
  summary: string
}

export interface Navigation {
  announcement_label?: string
  cta_href?: string
  cta_label?: string
  items?: { emphasis?: boolean; href: string; label: string }[]
}

export interface PackagePage {
  slug: string
  content: string
  description?: string
  order?: number
  sidebar_label?: string
  slug: string
  title: string
}

export interface PricingTier {
  id: string
  billing_hint?: string
  featured?: boolean
  features?: string[]
  name: string
  price_label: string
  summary: string
}

export interface ReferencePage {
  slug: string
  content: string
  description?: string
  order?: number
  sidebar_label?: string
  slug: string
  title: string
}

export interface SeoDefaults {
  canonical_base: string
  meta_description: string
  meta_title: string
  og_image?: string
}

export interface SettingsGroup {
  id: string
  items?: { hint?: string; label: string; status?: string; value: string }[]
  summary?: string
  title: string
}

export interface SiteSettings {
  default_locale: string
  og_image?: string
  site_name: string
  site_tagline?: string
  theme_name: string
}

export type UiCopy = Record<string, string>

export interface WorkQueueItem {
  id: string
  due_label?: string
  href?: string
  owner?: string
  priority?: 'low' | 'medium' | 'high'
  status?: 'queued' | 'active' | 'blocked' | 'done'
  summary: string
  title: string
}

export interface QueryBuilder<T> {
  locale(lang: string): QueryBuilder<T>
  where<K extends keyof T>(field: K, value: T[K]): QueryBuilder<T>
  sort<K extends keyof T>(field: K, order?: 'asc' | 'desc'): QueryBuilder<T>
  limit(n: number): QueryBuilder<T>
  offset(n: number): QueryBuilder<T>
  include(...fields: string[]): QueryBuilder<T>
  first(): T | undefined
  all(): T[]
}

export interface SingletonAccessor<T> {
  locale(lang: string): SingletonAccessor<T>
  include(...fields: string[]): SingletonAccessor<T>
  get(): T
}

export interface DictionaryAccessor {
  locale(lang: string): DictionaryAccessor
  get(): Record<string, string>
  get(key: string): string | undefined
  get(key: string, params: Record<string, string | number>): string
}

export interface DocumentQuery<T> {
  locale(lang: string): DocumentQuery<T>
  where<K extends keyof T>(field: K, value: T[K]): DocumentQuery<T>
  include(...fields: string[]): DocumentQuery<T>
  bySlug(slug: string): T | undefined
  first(): T | undefined
  all(): T[]
}

export declare function query(model: 'dashboard-stat'): QueryBuilder<DashboardStat>
export declare function query(model: 'feature'): QueryBuilder<Feature>
export declare function query(model: 'integration'): QueryBuilder<Integration>
export declare function query(model: 'pricing-tier'): QueryBuilder<PricingTier>
export declare function query(model: 'settings-group'): QueryBuilder<SettingsGroup>
export declare function query(model: 'work-queue-item'): QueryBuilder<WorkQueueItem>
export declare function query(model: string): QueryBuilder<Record<string, unknown>>

export declare function singleton(model: 'dashboard-overview'): SingletonAccessor<DashboardOverview>
export declare function singleton(model: 'footer'): SingletonAccessor<Footer>
export declare function singleton(model: 'hero'): SingletonAccessor<Hero>
export declare function singleton(model: 'navigation'): SingletonAccessor<Navigation>
export declare function singleton(model: 'seo-defaults'): SingletonAccessor<SeoDefaults>
export declare function singleton(model: 'site-settings'): SingletonAccessor<SiteSettings>
export declare function singleton(model: string): SingletonAccessor<Record<string, unknown>>

export declare function dictionary(model: 'ui-copy'): DictionaryAccessor
export declare function dictionary(model: string): DictionaryAccessor

export declare function document(model: 'changelog-entry'): DocumentQuery<ChangelogEntry>
export declare function document(model: 'docs-page'): DocumentQuery<DocsPage>
export declare function document(model: 'guide-page'): DocumentQuery<GuidePage>
export declare function document(model: 'package-page'): DocumentQuery<PackagePage>
export declare function document(model: 'reference-page'): DocumentQuery<ReferencePage>
export declare function document(model: string): DocumentQuery<Record<string, unknown>>

export interface ContentrainClient {
  query(model: 'dashboard-stat'): QueryBuilder<DashboardStat>
  query(model: 'feature'): QueryBuilder<Feature>
  query(model: 'integration'): QueryBuilder<Integration>
  query(model: 'pricing-tier'): QueryBuilder<PricingTier>
  query(model: 'settings-group'): QueryBuilder<SettingsGroup>
  query(model: 'work-queue-item'): QueryBuilder<WorkQueueItem>
  query(model: string): QueryBuilder<Record<string, unknown>>
  singleton(model: 'dashboard-overview'): SingletonAccessor<DashboardOverview>
  singleton(model: 'footer'): SingletonAccessor<Footer>
  singleton(model: 'hero'): SingletonAccessor<Hero>
  singleton(model: 'navigation'): SingletonAccessor<Navigation>
  singleton(model: 'seo-defaults'): SingletonAccessor<SeoDefaults>
  singleton(model: 'site-settings'): SingletonAccessor<SiteSettings>
  singleton(model: string): SingletonAccessor<Record<string, unknown>>
  dictionary(model: 'ui-copy'): DictionaryAccessor
  dictionary(model: string): DictionaryAccessor
  document(model: 'changelog-entry'): DocumentQuery<ChangelogEntry>
  document(model: 'docs-page'): DocumentQuery<DocsPage>
  document(model: 'guide-page'): DocumentQuery<GuidePage>
  document(model: 'package-page'): DocumentQuery<PackagePage>
  document(model: 'reference-page'): DocumentQuery<ReferencePage>
  document(model: string): DocumentQuery<Record<string, unknown>>
}

export declare function createContentrainClient(): ContentrainClient

